language: elixir
elixir: 1.0.0
otp_release:
  - 17.0
  - 17.1
  - 17.3
before_script:
  - "MIX_ENV=test mix do deps.get, compile"
after_success:
  - MIX_ENV=test mix coveralls.travis
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
